/*
  # Seed Terms for Chapter 5: HTML & CSS

  1. Data Added
    - 40 HTML & CSS terms for Chapter 5
    - Terms cover: HTML basics, CSS styling, layout, responsive design
    - Difficulty levels: 1-2

  2. Terms Include
    - HTML: html, tag, element, attribute, class, id
    - CSS: css, selector, property, box-model, flexbox, grid
    - Responsive: viewport, media-query, mobile-first
    - Accessibility: semantic-html, accessibility, aria
*/

INSERT INTO terms (id, term, term_ja, chapter_id, order_index, difficulty, one_liner, definition, mechanism, analogy, pitfall, related_terms, story_context)
VALUES
  ('html', 'HTML', 'エイチティーエムエル', 5, 1, 1, 'Webページの骨組みを作る言語', 'HyperText Markup Languageの略。Webページの構造を記述するための言語。見出し、段落、リンク、画像などの要素を「タグ」で囲んで表現する。', '<html>、<body>、<h1>、<p>などのタグを使って文書の構造を定義。ブラウザがこのファイルを読み込んで、Webページとして表示する。', '家の設計図で「ここが柱」「ここが壁」「ここがドア」と指示するようなもの。HTMLは「ここが見出し」「ここが段落」「ここがリンク」と構造を指示する。', 'HTMLだけでは見た目が質素。色や配置を整えるにはCSSが必要。HTMLは「骨組み」、CSSは「内装」と覚えよう。', ARRAY['css', 'tag', 'dom'], '建設現場に到着。HTMLくんが「僕は家の構造——柱や壁を担当」と自己紹介。'),
  ('css', 'CSS', 'シーエスエス', 5, 2, 1, 'Webページの見た目を整える言語', 'Cascading Style Sheetsの略。HTMLで作った構造に対して、色、サイズ、配置などの見た目（スタイル）を指定するための言語。', 'セレクタで対象を選び、プロパティと値でスタイルを指定する。例：h1 { color: blue; } は「h1タグを青色に」という意味。', '家の内装デザイン。壁紙の色、家具の配置、照明の明るさなど、見た目を美しく整える役割。構造（HTML）は変えずに見た目だけ変更できる。', 'CSSの「C」ascading（連鎖的）の意味は、後から書いたスタイルが優先されること。この「上書きルール」を理解しないと混乱する。', ARRAY['html', 'selector', 'property'], 'CSSちゃんが「私は内装——色や配置を担当」と自己紹介。「二人セットで、初めて素敵な家になるの」'),
  ('dom', 'DOM', 'ドム', 5, 3, 2, 'HTMLをツリー構造で表したもの', 'Document Object Modelの略。HTMLドキュメントをツリー構造のオブジェクトとして表現したもの。JavaScriptからページを操作するときに使う。', 'html → head, body → div, p, h1... のように親子関係でノードが連なる。document.getElementById() などでノードにアクセスできる。', '家族の家系図。html が先祖で、そこから body、div、p と子孫が枝分かれしていく構造。', 'DOMの操作は「重い」処理。頻繁に操作するとページが遅くなる。Reactなどが仮想DOMを使う理由の一つ。', ARRAY['html', 'element', 'javascript'], '「DOM は、HTML をツリー構造で表したもの。JavaScript からページを操作するときに使うよ」'),
  ('element', 'Element', '要素', 5, 4, 1, 'HTMLの1つの部品', '開始タグ、内容、終了タグを合わせた1つのまとまり。<p>これは段落です</p> 全体が1つの要素。', '要素は入れ子（ネスト）にできる。<div><p>テキスト</p></div> のように、要素の中に要素を入れられる。', 'レゴのブロック1個。ブロック（要素）を組み合わせて、大きな作品（ページ）を作る。', '「タグ」と「要素」を混同しがち。タグは <p> や </p> という記号、要素はタグと中身を含めた全体。', ARRAY['tag', 'attribute', 'dom'], '「Element（要素）は、タグと中身を合わせた全体のこと」と図で説明。'),
  ('tag', 'Tag', 'タグ', 5, 5, 1, 'HTMLの命令を囲む記号', '< > で囲まれたHTMLの命令。開始タグ <p> と終了タグ </p> でコンテンツを囲んで要素を作る。', '<タグ名>内容</タグ名> の形が基本。<img> や <br> のように終了タグがない「空要素」もある。', '本のしおり。「ここから見出し」「ここで見出し終わり」と範囲を示す目印。', 'タグを閉じ忘れると、レイアウトが崩れる原因になる。開いたら閉じるを徹底する。', ARRAY['element', 'attribute', 'html'], '「HTML は Tag（タグ）を使って構造を作るんだ」と HTMLくんが設計図を見せる。'),
  ('attribute', 'Attribute', '属性', 5, 6, 1, 'タグに追加する情報', 'タグに付加情報を与えるもの。属性名="値" の形式で開始タグ内に書く。', '<a href="https://example.com">リンク</a> の href が属性。id、class、src、alt なども属性。', '商品のラベル。商品（タグ）に「色：赤」「サイズ：L」のような追加情報を貼り付ける。', '属性名と値の間の = や、値を囲む引用符を忘れやすい。正確に書く習慣をつける。', ARRAY['tag', 'class', 'id'], '「Attribute（属性）は、タグに追加の情報を付けるもの」と href の例を示す。'),
  ('class', 'Class', 'クラス', 5, 7, 1, '複数の要素に同じ名前をつける属性', '要素にグループ名をつける属性。同じクラス名を持つ複数の要素に、まとめてスタイルを適用できる。', '<div class="card">...</div> で card クラスを付与。CSSでは .card { } でスタイル指定。複数のクラスも付けられる。', '学校のクラス（組）。「1組の生徒全員」のように、グループをまとめて指定できる。', 'class と className の違いに注意。HTMLでは class、JSXでは className を使う。', ARRAY['id', 'selector', 'attribute'], '「Class は、複数の要素に同じ名前をつけるとき」と CSSちゃんが説明。'),
  ('id', 'ID', 'アイディー', 5, 8, 1, 'たった1つの要素につける固有の名前', 'ページ内で唯一の要素を特定するための属性。同じIDは1ページに1つだけ使用可能。', '<div id="main-header">...</div> で ID を付与。CSSでは #main-header { } でスタイル指定。', '社員番号。会社（ページ）内で一人（一要素）に一つだけ割り当てられる固有の番号。', '同じIDを複数の要素に使うのはNG。動作はするが、HTMLの仕様違反でバグの原因になる。', ARRAY['class', 'selector', 'attribute'], '「ID は、たったひとつの要素につける固有の名前よ」'),
  ('selector', 'Selector', 'セレクタ', 5, 9, 1, 'どの要素にスタイルを適用するか選ぶ方法', 'CSSでスタイルを適用する対象を指定する記法。タグ名、クラス、ID、属性などで要素を選択できる。', 'div { } はタグ、.card { } はクラス、#header { } はIDで選択。組み合わせも可能。', '人混みの中から「赤い帽子の人」「メガネをかけた人」と条件で人を選ぶようなもの。', 'セレクタが複雑になると、どの要素に適用されるかわかりにくくなる。シンプルに保つ。', ARRAY['class', 'id', 'property'], '「Selector は、どの要素にスタイルを適用するか選ぶ方法」'),
  ('property', 'Property', 'プロパティ', 5, 10, 1, '何を変えるかを指定するもの', 'CSSで変更したいスタイルの種類。color（色）、font-size（文字サイズ）、margin（余白）など。', 'セレクタ { プロパティ: 値; } の形で使う。例：h1 { color: blue; font-size: 24px; }', '調整つまみの名前。「音量」「明るさ」「色合い」のように、何を調整するかを示す。', 'プロパティ名はハイフンで区切る（font-size）。JavaScriptではキャメルケース（fontSize）になる。', ARRAY['value', 'selector', 'css'], '「Property（プロパティ）と Value（値）でスタイルを指定するの」'),
  ('value', 'Value', '値', 5, 11, 1, 'プロパティに設定する具体的な内容', 'CSSプロパティに対して設定する具体的な値。色名、数値、キーワードなど、プロパティによって使える値は異なる。', 'color: blue; の blue、font-size: 16px; の 16px、display: flex; の flex が値。', '調整つまみを回して設定する「数値」。音量を「7」に、明るさを「最大」に設定するようなもの。', '単位（px、em、rem、%など）を忘れると効かないことがある。数値には適切な単位をつける。', ARRAY['property', 'css', 'unit'], '「color: blue; の blue が Value（値）よ」'),
  ('style', 'Style', 'スタイル', 5, 12, 1, '要素の見た目の設定', '要素の視覚的な表現に関する設定全般。色、サイズ、フォント、余白、配置など。', 'CSSで定義するか、HTMLの style 属性で直接指定する。style="color: red;" のような形式。', '服のコーディネート。色、形、素材を組み合わせて見た目を整える。', 'style属性（インラインスタイル）は便利だが、保守性が下がるので多用は避ける。', ARRAY['css', 'stylesheet', 'inline-style'], '「Style の書き方は3種類あるの」と CSSちゃんが説明を始める。'),
  ('stylesheet', 'Stylesheet', 'スタイルシート', 5, 13, 1, 'スタイルをまとめたファイル', 'CSSのスタイル定義をまとめた外部ファイル（.cssファイル）。複数のHTMLページで共有できる。', '<link rel="stylesheet" href="style.css"> でHTMLに読み込む。サイト全体のスタイルを一元管理できる。', 'ドレスコード集。「会議のときはスーツ」「カジュアルフライデーは私服OK」のようなルール集。', 'ファイルパスを間違えるとスタイルが適用されない。パスの指定を正確に。', ARRAY['css', 'style', 'link'], '「Stylesheet は、別ファイルにCSSをまとめる方法。一番おすすめよ」'),
  ('inline-style', 'Inline style', 'インラインスタイル', 5, 14, 1, 'タグに直接書くスタイル', 'HTMLタグのstyle属性に直接CSSを書く方法。その要素だけに適用される。', '<p style="color: red; font-size: 16px;">テキスト</p> のように属性として記述する。', 'その場で服を直す応急処置。急ぎのときは便利だが、整理されていないので後で困る。', '再利用できず、HTMLが読みにくくなる。緊急時やJSでの動的変更以外では避ける。', ARRAY['style', 'stylesheet', 'css'], '「Inline style は、タグに直接書く方法。緊急のときだけにしてね」'),
  ('box-model', 'Box model', 'ボックスモデル', 5, 15, 2, '要素を箱として扱うレイアウトの考え方', '全てのHTML要素を「箱」として扱い、content、padding、border、margin の4層で構成するというCSSのレイアウトモデル。', '内側から content（内容）→ padding（内側余白）→ border（枠線）→ margin（外側余白）の順。', 'プレゼントの箱。中身（content）、緩衝材（padding）、箱自体（border）、箱の周りの空間（margin）。', 'width を指定しても、padding と border の分だけ実際の幅が大きくなる。box-sizing: border-box; で解決。', ARRAY['margin', 'padding', 'border'], '「すべての要素は『箱』なの」と CSSちゃんがボックスモデルの図を描く。'),
  ('margin', 'Margin', 'マージン', 5, 16, 1, '要素の外側の余白', '要素の外側に作る余白。隣り合う要素との間隔を調整するために使う。', 'margin: 10px; で上下左右10px。margin: 10px 20px; で上下10px、左右20px。方向ごとの指定も可能。', '人と人の間の距離。「パーソナルスペース」として、他の人（要素）との間隔を確保する。', 'margin の相殺（collapse）に注意。上下の margin が重なると、大きい方だけが適用される。', ARRAY['padding', 'box-model', 'border'], '「Margin は要素の外側の余白」とボックスモデル図の一番外側を指す。'),
  ('padding', 'Padding', 'パディング', 5, 17, 1, '要素の内側の余白', '要素の内側、コンテンツと border の間に作る余白。背景色は padding 領域にも適用される。', 'padding: 10px; で上下左右10px。指定方法は margin と同じ。', '段ボール箱の中の緩衝材。中身（コンテンツ）を守るための内側のスペース。', 'padding を増やすと要素全体のサイズが大きくなる（box-sizing: content-box; の場合）。', ARRAY['margin', 'box-model', 'border'], '「Padding は要素の内側の余白」'),
  ('border', 'Border', 'ボーダー', 5, 18, 1, '要素の枠線', '要素の周りに表示する枠線。太さ、スタイル、色を指定できる。', 'border: 1px solid black; で太さ1px、実線、黒色の枠線。border-radius で角を丸くできる。', '額縁。絵（コンテンツ）の周りを囲んで、見栄えを良くする装飾。', 'border も要素のサイズに含まれる（box-sizing: content-box; の場合）。レイアウト計算時に注意。', ARRAY['margin', 'padding', 'box-model'], '「Border は要素の枠線」'),
  ('display', 'Display', 'ディスプレイ', 5, 19, 2, '要素の表示方法を決めるプロパティ', '要素がどのように表示され、レイアウトに参加するかを決めるCSSプロパティ。', 'block は縦に積まれる、inline は横に並ぶ、none は非表示、flex はフレックスボックス、grid はグリッドレイアウト。', '商品の陳列方法。「棚に縦に積む（block）」「横一列に並べる（inline）」「倉庫にしまう（none）」。', 'display: none; は要素がなくなったかのように扱われる。visibility: hidden; は空間を残して非表示。', ARRAY['position', 'flexbox', 'grid'], '「Display と Position で配置を決めるんだ」と HTMLくんが説明。'),
  ('position', 'Position', 'ポジション', 5, 20, 2, '要素の配置方法を決めるプロパティ', '要素をどのように配置するかを決めるCSSプロパティ。top、right、bottom、left と組み合わせて位置を指定。', 'static（通常）、relative（相対）、absolute（絶対）、fixed（固定）、sticky（スティッキー）がある。', '家具の配置方法。「部屋の流れに従う（static）」「基準位置からずらす（relative）」「自由に置く（absolute）」。', 'absolute は親の position が static だとうまく機能しない。親に relative を指定する必要がある。', ARRAY['display', 'z-index', 'flexbox'], '「position: relative は元の位置基準で調整、absolute は親要素基準で自由配置」'),
  ('flexbox', 'Flexbox', 'フレックスボックス', 5, 21, 2, '1方向の並びが得意なレイアウト方法', '要素を横一列または縦一列に柔軟に配置できるCSSレイアウト方式。配置、間隔、順序の調整が簡単。', 'display: flex; を親に指定。justify-content で主軸方向、align-items で交差軸方向の配置を調整。', '本棚の整理。本を横一列に並べて、「左詰め」「中央揃え」「均等配置」などを簡単に指定できる。', 'Flexbox は1次元（行または列）向け。2次元レイアウトには Grid を使う方が適している。', ARRAY['grid', 'display', 'justify-content'], '「最近は Flexbox と Grid が主流よ」と CSSちゃんが説明。「1方向の並びが得意」'),
  ('grid', 'Grid', 'グリッド', 5, 22, 2, '2次元のレイアウトが得意なレイアウト方法', '要素を行と列の2次元グリッドに配置できるCSSレイアウト方式。複雑なページレイアウトに適している。', 'display: grid; を親に指定。grid-template-columns、grid-template-rows でグリッドを定義。', 'エクセルのセル。行と列で区切られたマス目に、要素を自由に配置できる。', 'Grid は強力だが、シンプルな横並びには Flexbox の方が簡単。目的に応じて使い分ける。', ARRAY['flexbox', 'display', 'layout'], '「Grid は、2方向のレイアウトが得意。複雑なページ構成に使うわ」'),
  ('z-index', 'Z-index', 'ゼットインデックス', 5, 23, 2, '要素の重なり順を決める数値', 'position が static 以外の要素の、前後の重なり順を指定するCSSプロパティ。数値が大きいほど手前に表示。', 'z-index: 1; より z-index: 10; の要素が手前に来る。同じ値なら HTML の記述順。', '紙を重ねる順番。z-index: 10 の紙は z-index: 1 の紙の上に置かれる。', 'z-index はスタッキングコンテキスト内でのみ比較される。親子関係によっては期待通りにならないことも。', ARRAY['position', 'layer', 'stacking'], '「Z-index は、要素の重なり順を決める数値よ。数字が大きいほど手前に表示されるの」'),
  ('overflow', 'Overflow', 'オーバーフロー', 5, 24, 2, 'はみ出した内容の扱いを決める', '要素の内容がボックスからはみ出した場合の表示方法を指定するCSSプロパティ。', 'visible（はみ出して表示）、hidden（隠す）、scroll（スクロール）、auto（必要時スクロール）。', 'コップの水があふれたとき。「そのまま（visible）」「拭き取る（hidden）」「受け皿を用意（scroll）」。', 'overflow: hidden; は要素からはみ出す子要素も隠れる。意図しない表示崩れの原因になることも。', ARRAY['box-model', 'scroll', 'height'], '「Overflow は、はみ出した内容をどうするか。scroll にすればスクロールできるわ」'),
  ('viewport', 'Viewport', 'ビューポート', 5, 25, 2, 'ブラウザの表示領域', 'Webページが表示されるブラウザウィンドウの可視領域。デバイスや画面サイズによって異なる。', 'vw（viewport width）、vh（viewport height）という単位で、画面サイズに対する割合を指定できる。', '窓から見える景色の範囲。窓（ブラウザ）のサイズによって、見える範囲（viewport）が変わる。', 'モバイルの viewport は注意が必要。<meta name="viewport"> タグでの設定が重要。', ARRAY['responsive-design', 'vw', 'vh'], '「Viewport は、ブラウザの表示領域のこと」'),
  ('responsive-design', 'Responsive design', 'レスポンシブデザイン', 5, 26, 2, '画面サイズに合わせてデザインを変える手法', 'PC、タブレット、スマートフォンなど、様々な画面サイズに対応してレイアウトを自動調整するWebデザイン手法。', 'メディアクエリで画面幅に応じたスタイルを定義。フレキシブルなグリッドと画像サイズを使用する。', '水が容器の形に合わせて変形するように、コンテンツが画面サイズに合わせて最適な形に変わる。', 'PC向けを先に作ってから縮小するより、モバイルファーストの方が効率的なことが多い。', ARRAY['media-query', 'viewport', 'mobile-first'], '「スマホでもパソコンでもきれいに見せたいよね」と Responsive design の説明へ。'),
  ('responsive-mode', 'Responsive mode', 'レスポンシブモード', 5, 27, 1, 'ブラウザで画面サイズをシミュレーションする機能', '開発者ツールに搭載された、様々な画面サイズでの表示を確認できる機能。実機がなくてもテスト可能。', 'F12キーで開発者ツールを開き、デバイスツールバーをクリック。iPhone、Pixel など様々なデバイスをシミュレート。', '試着室の鏡。実際に外に出なくても（実機がなくても）、服の見え方（表示）を確認できる。', 'シミュレーションと実機では動作が異なることもある。重要な確認は実機でも行う。', ARRAY['responsive-design', 'dev-tools', 'viewport'], '「Responsive mode は、ブラウザでいろんな画面サイズをシミュレーションする機能よ」'),
  ('media-query', 'Media query', 'メディアクエリ', 5, 28, 2, '条件に応じてスタイルを切り替える仕組み', '画面幅などの条件に基づいて、適用するCSSを切り替える仕組み。レスポンシブデザインの核となる技術。', '@media (max-width: 768px) { } で768px以下の時のスタイルを定義。min-width、orientation なども使える。', '季節に応じた服装。「気温が10度以下なら（条件）、コートを着る（スタイル）」。', 'ブレークポイントの値はデバイスの実態に合わせる。768px、1024px などがよく使われる。', ARRAY['responsive-design', 'breakpoint', 'viewport'], '「Media query を使うの」と @media の例を示す。'),
  ('mobile-first', 'Mobile-first', 'モバイルファースト', 5, 29, 2, 'まずスマホ向けに作って、大画面に拡張する考え方', '最初にモバイル（スマホ）向けのデザインを作り、画面が大きくなるにつれて機能やレイアウトを追加していくアプローチ。', 'ベースのCSSはモバイル向けに書き、min-width のメディアクエリで大画面向けスタイルを追加。', '核となる荷物だけで出発し、必要に応じて追加していく旅行。最初から大荷物より効率的。', '既存のPC向けサイトをモバイル対応させる場合は、逆のアプローチになることもある。', ARRAY['responsive-design', 'media-query', 'viewport'], '「Mobile-first は、まずスマホ向けに作って、大きい画面向けに拡張する考え方」'),
  ('semantic-html', 'Semantic HTML', 'セマンティックHTML', 5, 30, 2, '意味のあるタグを使ったHTML', '要素の意味・役割を表すタグを適切に使用したHTML。<div>だらけではなく、<header>、<nav>、<main>、<article>などを使う。', 'コンテンツの意味に合ったタグを選ぶ。検索エンジンやスクリーンリーダーが内容を理解しやすくなる。', '本の目次。「序章」「第1章」「まとめ」と構造がわかる目次のように、ページの構造が明確になる。', '<div> と <span> は意味を持たないタグ。レイアウト目的でのみ使い、意味のある要素には適切なタグを。', ARRAY['accessibility', 'aria', 'seo'], '「Semantic HTML を心がけてね」と HTMLくんが説明。「<div> ばかり使わずに、意味のあるタグを使うんだ」'),
  ('accessibility', 'Accessibility', 'アクセシビリティ', 5, 31, 2, '誰でも使えるようにする配慮', '障害の有無や環境に関わらず、すべての人がWebサイトを利用できるようにすること。a11y と略されることも。', '適切なコントラスト、キーボード操作対応、スクリーンリーダー対応、代替テキストの提供などを行う。', 'バリアフリー設計。車椅子の人も、目の見えない人も、誰もが建物を利用できるようにする設計思想。', '「見た目がきれい」と「アクセシブル」は別。低コントラストのおしゃれなデザインは読みにくいことも。', ARRAY['aria', 'semantic-html', 'alt'], '「Accessibility——誰でも使えるサイトを目指そう」'),
  ('aria', 'ARIA', 'エリア', 5, 32, 2, 'スクリーンリーダーに情報を伝える属性', 'Accessible Rich Internet Applications の略。HTMLに追加情報を付与して、支援技術（スクリーンリーダーなど）の理解を助ける属性群。', 'aria-label、aria-hidden、role などの属性を使用。視覚的には変化がないが、支援技術に情報を提供する。', '目の見えない人のための音声ガイド。「ここにボタンがあります」「これはメニューです」と説明を追加する。', 'ARIAの使いすぎは逆効果になることも。まずは正しいセマンティックHTMLを使い、必要な場合のみARIAを追加。', ARRAY['accessibility', 'semantic-html', 'screen-reader'], '「ARIA 属性は、目の見えない人が使うスクリーンリーダーに情報を伝えるための属性よ」'),
  ('embed-code', 'Embed code', '埋め込みコード', 5, 33, 1, '外部コンテンツを埋め込むためのコード', 'YouTube、Googleマップ、SNS投稿などの外部コンテンツを自分のサイトに埋め込むためのHTMLコード。', 'サービス側が提供する「埋め込みコード」をコピーしてHTMLに貼り付ける。通常は iframe を使用。', '雑誌の切り抜きを自分のスクラップブックに貼るようなもの。他のサービスの内容を自分のサイトで表示。', '埋め込みコンテンツは読み込みが遅くなる原因になることも。必要な場所だけに使用する。', ARRAY['iframe', 'youtube', 'widget'], '「他のサイトの内容を埋め込むこともできるよ」'),
  ('iframe', 'iFrame', 'アイフレーム', 5, 34, 2, '別のページを枠の中に表示する要素', 'Inline Frame の略。HTMLページ内に別のHTMLページを埋め込んで表示するための要素。', '<iframe src="https://example.com"></iframe> で外部ページを表示。YouTube、Googleマップの埋め込みに使用。', '額縁の中に別の絵を飾る。ページという「部屋」の中に、別のページという「窓」を作る。', 'セキュリティ上、すべてのサイトが iframe で表示できるわけではない。X-Frame-Options で制限されていることも。', ARRAY['embed-code', 'src', 'sandbox'], '「iFrame は、別のページを枠の中に表示する方法」'),
  ('container', 'Container', 'コンテナ', 5, 35, 1, '要素をまとめて囲む箱', '複数の要素をグループ化して囲む親要素。レイアウトの制御や、スタイルの一括適用に使う。', '<div class="container">...</div> のように、関連する要素を囲む。幅の制御やセンタリングに便利。', '段ボール箱。複数の商品（要素）をまとめて1つの箱（コンテナ）に入れて管理する。', 'container の入れ子が深くなりすぎないよう注意。構造はできるだけシンプルに。', ARRAY['wrapper', 'div', 'layout'], '「Container と Wrapper は、要素をまとめて囲む箱よ。レイアウトを整えるのに使うの」'),
  ('wrapper', 'Wrapper', 'ラッパー', 5, 36, 1, '要素を包む外側の要素', '他の要素を包み込む（ラップする）外側の要素。Container と同様の用途で使われることが多い。', '<div class="wrapper">...</div> で要素を囲む。命名は慣習で、機能的には container と同じ。', 'プレゼントの包装紙。中身（子要素）を包んで、見た目を整えたり、まとめたりする。', 'wrapper と container の使い分けはプロジェクトのルールによる。一貫性を持って使い分ける。', ARRAY['container', 'div', 'layout'], 'Container と一緒に説明。「Wrapper も同じような役割」'),
  ('float', 'Float', 'フロート', 5, 37, 2, '要素を左右に浮かせる古いレイアウト手法', '要素を左または右に浮かせ、テキストを回り込ませるCSSプロパティ。昔は段組みレイアウトにも使われた。', 'float: left; で左に浮かせる。後続の要素が回り込む。clear で回り込みを解除。', '新聞の写真と文章。写真を「浮かせて」、文章がその周りを流れるように配置する。', 'レイアウト目的の float は非推奨。現在は Flexbox や Grid を使う。画像の回り込みには今でも有効。', ARRAY['clear', 'flexbox', 'grid'], '「昔は Float を使っていたけど、今は Flexbox と Grid の方が便利よ」'),
  ('clear', 'Clear', 'クリア', 5, 38, 2, 'float の回り込みを解除する', 'float による回り込みを解除するCSSプロパティ。floatした要素の影響を受けないようにする。', 'clear: both; で左右両方の回り込みを解除。clear: left; や clear: right; で片方だけ解除も可能。', '「ここから新しい段落」という区切り線。前の浮いた要素の影響を断ち切る。', 'clearfix という手法がよく使われた。今は overflow: hidden; や display: flow-root; も代替になる。', ARRAY['float', 'clearfix'], '「Float を使ったら Clear で解除してね」'),
  ('pseudo-class', 'Pseudo-class', '擬似クラス', 5, 39, 2, '要素の状態を表すセレクタ', '要素の特定の状態（マウスオーバー、フォーカス、最初の子など）を表すセレクタ。コロン1つ（:）で始まる。', 'a:hover（ホバー時）、input:focus（フォーカス時）、li:first-child（最初の子要素）など。', '人の状態を表す形容詞。「走っている人」「座っている人」のように、状態で対象を絞り込む。', ':hover はモバイルでは使いにくい（タップしないとホバーできない）。タッチ対応を考慮する。', ARRAY['pseudo-element', 'selector', 'hover-state'], '「Pseudo-class は :hover など、状態を表すセレクタ」'),
  ('pseudo-element', 'Pseudo-element', '擬似要素', 5, 40, 2, '要素の一部を装飾するセレクタ', '要素の特定の部分（前後、最初の文字、最初の行など）を対象にするセレクタ。コロン2つ（::）で始まる。', 'p::first-letter（最初の文字）、div::before（要素の前）、div::after（要素の後）など。', '文章の一部だけをハイライト。「最初の文字だけ大きく」「文の後に記号を追加」などの装飾。', '::before と ::after は content プロパティが必須。content: ""; だけでも指定が必要。', ARRAY['pseudo-class', 'selector', 'before-after'], '「Pseudo-element は ::before など、要素の一部を装飾するセレクタ」')
ON CONFLICT (id) DO UPDATE SET
  term = EXCLUDED.term,
  term_ja = EXCLUDED.term_ja,
  chapter_id = EXCLUDED.chapter_id,
  order_index = EXCLUDED.order_index,
  difficulty = EXCLUDED.difficulty,
  one_liner = EXCLUDED.one_liner,
  definition = EXCLUDED.definition,
  mechanism = EXCLUDED.mechanism,
  analogy = EXCLUDED.analogy,
  pitfall = EXCLUDED.pitfall,
  related_terms = EXCLUDED.related_terms,
  story_context = EXCLUDED.story_context;
