/*
  # Seed Terms for Chapter 7: JavaScript & TypeScript

  1. Data Added
    - 40 JavaScript/TypeScript terms for Chapter 7
    - Terms cover: ES6 features, async programming, DOM, array methods
    - Difficulty levels: 1-2

  2. Terms Include
    - Basics: javascript, typescript, es6, let, const
    - Functions: arrow-function, async, await, promise
    - Modules: module, import, export
    - Array methods: map, filter, reduce, forEach, find
*/

INSERT INTO terms (id, term, term_ja, chapter_id, order_index, difficulty, one_liner, definition, mechanism, analogy, pitfall, related_terms, story_context)
VALUES
  ('javascript', 'JavaScript', 'ジャバスクリプト', 7, 1, 1, 'Webページに動きを与えるプログラミング言語', 'Webブラウザ上で動作するプログラミング言語。ページに対話性や動的な機能を追加できる。現在はサーバーサイド（Node.js）でも使われる。', 'ブラウザに内蔵されたJavaScriptエンジンが実行。DOM操作、イベント処理、非同期通信など幅広い機能を持つ。', '家の電気系統。HTML（構造）とCSS（内装）でできた家に、スイッチを押したら電気がつく「仕掛け」を作る。', '「Java」と「JavaScript」は全くの別物！名前が似ているだけで、文法も用途も違う。', ARRAY['typescript', 'es6', 'node-js'], '道場に入ると、JSマスターが「JavaScript は Web に命を吹き込む言語だ」と説明。'),
  ('typescript', 'TypeScript', 'タイプスクリプト', 7, 2, 2, '型を追加して安全にしたJavaScript', 'JavaScriptに静的型付けを追加した言語。Microsoftが開発。コンパイル時にエラーを検出でき、大規模開発に向いている。', 'TypeScriptで書いたコードは、コンパイルされてJavaScriptに変換される。型情報は実行時には消える。', '書類のフォーマット。「ここには数字を」「ここには文字を」と決まっているので、記入ミスを防げる。', '学習コストはあるが、大規模開発ではバグが減り、結果的に時間の節約になる。', ARRAY['javascript', 'type-alias', 'interface'], '「TypeScript は、JavaScript をより安全に書くための拡張だ」'),
  ('es6', 'ES6', 'イーエスシックス', 7, 3, 2, 'JavaScriptの大型アップデート（2015年）', 'ECMAScript 2015の通称。let/const、アロー関数、クラス、モジュールなど、多くの新機能が追加された重要なバージョン。', 'JavaScriptの標準仕様はECMAScriptで定められている。ES6以降、毎年新機能が追加されている。', '大型アップデート。スマホのOSが大幅に進化して、新しい便利機能がたくさん使えるようになったようなもの。', '古いブラウザはES6をサポートしないことがある。Babelなどでトランスパイルして対応する。', ARRAY['ecmascript', 'let', 'const', 'arrow-function'], '「ES6 で JavaScript は大きく進化した。let、const、アロー関数……現代の基本だ」'),
  ('ecmascript', 'ECMAScript', 'エクマスクリプト', 7, 4, 2, 'JavaScriptの標準仕様', 'JavaScriptの言語仕様を定めた標準規格。ECMA International という団体が策定。ES6、ES2020などはそのバージョン。', 'ブラウザベンダー（Google、Mozilla、Apple等）はこの仕様に従ってJavaScriptエンジンを実装する。', '法律や規格。「JavaScriptはこう動くべき」というルールブック。各ブラウザはこれに従う。', 'ECMAScriptとJavaScriptはほぼ同義だが、厳密にはECMAScriptが仕様、JavaScriptがその実装。', ARRAY['es6', 'javascript'], '「ECMAScript は JavaScript の仕様書だ。これに従って言語が進化していく」'),
  ('let', 'Let', 'レット', 7, 5, 1, '再代入可能な変数を宣言するキーワード', 'ブロックスコープを持つ変数を宣言するキーワード。後から値を変更できる。ES6で導入された。', 'let x = 10; で宣言し、x = 20; で再代入可能。ブロック { } の中でのみ有効。', '書き換え可能なホワイトボード。一度書いた内容を消して、別の内容を書ける。', 'varは使わずletを使う。varは関数スコープで、意図しない動作の原因になりやすい。', ARRAY['const', 'variable', 'block-scope'], '「let は再代入できる変数。const は再代入できない定数。使い分けるのだ」'),
  ('const', 'Const', 'コンスト', 7, 6, 1, '再代入できない定数を宣言するキーワード', '一度値を代入したら変更できない変数を宣言するキーワード。ブロックスコープを持つ。ES6で導入された。', 'const PI = 3.14; で宣言。PI = 3; のように再代入しようとするとエラー。', '刻印された石板。一度刻んだら変更できない。不変の値を保存するのに使う。', 'constで宣言したオブジェクトや配列の「中身」は変更できる。再代入ができないだけ。', ARRAY['let', 'constant', 'block-scope'], '「基本は const を使え。変更が必要なときだけ let を使うのが良い作法だ」'),
  ('arrow-function', 'Arrow function', 'アロー関数', 7, 7, 1, '=> を使った短い関数の書き方', 'ES6で導入された関数の短縮記法。=> を使って簡潔に書ける。thisの挙動が通常の関数と異なる。', 'const add = (a, b) => a + b; のように書く。引数が1つなら括弧も省略可能。', '速記術。長い文章を短い記号で書く。同じ意味だけど、見た目がコンパクトになる。', 'アロー関数は自分自身の this を持たない。イベントハンドラで this を使うときは注意。', ARRAY['function', 'es6', 'this-keyword'], '「Arrow function（アロー関数）は、関数を短く書く現代の作法だ」'),
  ('async', 'Async', 'アシンク', 7, 8, 2, '非同期関数を宣言するキーワード', '関数の前につけて、その関数が非同期処理を行うことを示すキーワード。常にPromiseを返す。', 'async function fetchData() { ... } で宣言。中で await を使って非同期処理の完了を待てる。', '「お待ちください」の札。処理に時間がかかることを事前に宣言しておく。', 'async関数の戻り値は常にPromise。直接値を返しているように見えても、Promiseでラップされる。', ARRAY['await', 'promise', 'fetch'], '「Async と Await は、非同期処理を同期的に書けるようにする現代の技だ」'),
  ('await', 'Await', 'アウェイト', 7, 9, 2, 'Promiseの完了を待つキーワード', 'async関数内でPromiseの解決を待つキーワード。非同期処理を同期的なコードのように書ける。', 'const data = await fetch(url); で、fetch完了まで次の行に進まない。エラーはtry/catchで捕捉。', '「待って」の一言。料理が出てくるまで待つように、データが届くまで待つ。', 'awaitはasync関数の中でしか使えない。トップレベルで使う場合は別の対応が必要。', ARRAY['async', 'promise', 'try-catch'], '「Await で処理の完了を待つ。これで非同期処理が読みやすくなる」'),
  ('promise', 'Promise', 'プロミス', 7, 10, 2, '「いつか結果を届ける」という約束', '非同期処理の結果を表すオブジェクト。処理中（pending）、成功（fulfilled）、失敗（rejected）の3状態を持つ。', 'new Promise((resolve, reject) => { ... }) で作成。成功時はresolve、失敗時はrejectを呼ぶ。', '引換券。「後で商品をお届けします」という約束。届いたら（fulfilled）受け取り、届かなかったら（rejected）クレーム。', 'Promiseチェーンが深くなると読みにくい。async/awaitを使うと見通しが良くなる。', ARRAY['async', 'await', 'then-catch'], '「Promise は、非同期処理の結果を表す『約束』だ」'),
  ('fetch', 'Fetch', 'フェッチ', 7, 11, 1, 'サーバーからデータを取得するAPI', 'HTTPリクエストを送信してデータを取得するためのWeb API。Promiseを返し、非同期で動作する。', 'fetch(url).then(res => res.json()).then(data => ...) または async/awaitで使用。', '出前の注文。電話（fetch）して、料理（データ）が届くのを待つ。', 'fetchはHTTPエラー（404、500など）でもrejectしない。response.okをチェックする必要がある。', ARRAY['promise', 'async', 'api-call'], '「Fetch は、サーバーからデータを取ってくる術だ」'),
  ('then-catch', 'Then/catch', 'ゼン・キャッチ', 7, 12, 2, 'Promiseの成功・失敗を処理するメソッド', 'Promiseの結果を処理するメソッド。then()は成功時、catch()は失敗時の処理を指定する。', 'promise.then(result => {...}).catch(error => {...}) のようにチェーンで繋げる。', '「うまくいったら→こうする、失敗したら→こうする」という条件分岐を事前に決めておく。', 'catchを書かないとエラーが握りつぶされる。必ずエラーハンドリングを書く。', ARRAY['promise', 'async', 'await'], '「Then と Catch で、成功と失敗の処理を分ける」'),
  ('spread-operator', 'Spread operator', 'スプレッド演算子', 7, 13, 2, '配列やオブジェクトを展開する「...」', '...を使って配列やオブジェクトの要素を展開する演算子。コピーや結合に便利。', '[...arr1, ...arr2] で配列結合、{...obj, newProp: value} でオブジェクトにプロパティ追加。', 'カードの束をテーブルに広げる動作。まとまっていたものをバラバラに展開する。', 'スプレッドはシャローコピー（浅いコピー）。ネストしたオブジェクトは参照のまま。', ARRAY['destructuring', 'array', 'object'], '「Spread operator（...）は、配列やオブジェクトを展開する術だ」'),
  ('destructuring', 'Destructuring', '分割代入', 7, 14, 2, '配列やオブジェクトから値を取り出す構文', '配列やオブジェクトの要素を、変数に簡潔に代入する構文。ES6で導入された。', 'const [a, b] = [1, 2]; や const {name, age} = person; のように書く。', 'プレゼントの箱を開けて、中身を別々の場所に置く。一度に複数の値を取り出せる。', '存在しないプロパティを分割代入すると undefined になる。デフォルト値を設定できる。', ARRAY['spread-operator', 'array', 'object'], '「Destructuring は、配列やオブジェクトから値を取り出す構文だ」'),
  ('module', 'Module', 'モジュール', 7, 15, 2, 'コードを分割して管理する仕組み', 'コードを複数のファイルに分割し、必要な部分だけを読み込む仕組み。再利用性と保守性を高める。', 'exportで公開し、importで読み込む。ES6モジュールはブラウザでもNode.jsでも使える。', 'レゴのパーツ。必要なパーツだけを取り出して組み合わせる。全部一緒にする必要はない。', '循環参照（AがBを、BがAをimport）に注意。設計を見直す必要がある。', ARRAY['import', 'export', 'modularity'], '「Module で、コードを分割して管理する。これが現代の作法だ」'),
  ('import', 'Import', 'インポート', 7, 16, 1, '他のモジュールから機能を読み込む', '別のファイルからエクスポートされた関数、変数、クラスなどを読み込むキーワード。', 'import { func } from ''./module.js''; や import func from ''./module.js''; の形式で使う。', '図書館から本を借りる。必要な本（機能）を借りてきて、自分の作業で使う。', '名前付きエクスポートとデフォルトエクスポートで import の書き方が異なる。', ARRAY['export', 'module', 'default-export'], '「Import と Export で、モジュール間の連携を行う」'),
  ('export', 'Export', 'エクスポート', 7, 17, 1, '他のモジュールに機能を公開する', 'モジュールから関数、変数、クラスなどを外部に公開するキーワード。importで読み込める。', 'export const func = () => {}; や export { func, variable }; の形式で使う。', 'お店で商品を並べる。他の人（モジュール）が買える（importできる）ように公開する。', '何でもexportするのではなく、外部に必要なものだけを公開する。カプセル化を意識。', ARRAY['import', 'module', 'default-export'], '「Export で公開し、Import で読み込む。これがモジュールの基本だ」'),
  ('default-export', 'Default export', 'デフォルトエクスポート', 7, 18, 2, 'モジュールの主要なエクスポート', 'モジュールから1つだけ指定できる「主要な」エクスポート。import時に好きな名前で受け取れる。', 'export default function() {}; で公開し、import anyName from ''./module''; で受け取る。', 'お店の「看板商品」。一番のおすすめ品。他にも商品はあるけど、これがメイン。', '1モジュールにdefault exportは1つだけ。名前付きexportと併用可能。', ARRAY['named-export', 'import', 'module'], '「Default export は、そのモジュールのメイン機能を示す」'),
  ('named-export', 'Named export', '名前付きエクスポート', 7, 19, 2, '名前を指定してエクスポート', '関数や変数を名前付きでエクスポートする方法。import時に同じ名前で受け取る必要がある。', 'export { func, variable }; で公開し、import { func, variable } from ''./module''; で受け取る。', '商品に名前タグをつけて販売。「この名前の商品をください」と指定して買う。', 'import時に名前を間違えるとエラー。asを使ってリネームも可能。', ARRAY['default-export', 'import', 'module'], '「Named export は、名前を指定して公開する。複数公開できる」'),
  ('barrel-exports', 'Barrel exports', 'バレルエクスポート', 7, 20, 2, '複数モジュールをまとめて再エクスポート', '複数のモジュールを1つのindex.jsファイルからまとめて再エクスポートするパターン。import文を簡潔にできる。', 'index.jsで export { a } from ''./a''; export { b } from ''./b''; とし、外部から一括importできる。', '総合受付。各部署（モジュール）への窓口を一か所に集約して、利用者がアクセスしやすくする。', 'バレルが大きくなりすぎると、ツリーシェイキングに影響することがある。', ARRAY['export', 'import', 'module'], '「Barrel exports は、複数のモジュールをまとめて公開するテクニックだ」'),
  ('this-keyword', 'This keyword', 'thisキーワード', 7, 21, 2, '「自分自身」を指す特別な変数', '関数やメソッドの中で、その関数を呼び出したオブジェクト自身を参照する特別なキーワード。', '呼び出し方によって this が指すものが変わる。メソッドとして呼ぶとそのオブジェクト、単独で呼ぶとundefined（strictモード）。', '「私」という言葉。誰が言ったかによって、指す人が変わる。', 'アロー関数は自分の this を持たない。外側の this を引き継ぐ。この違いを理解することが重要。', ARRAY['method', 'arrow-function', 'object'], '「This は、呼び出し元を指す。これを理解することが JavaScript 修行の山場だ」'),
  ('event', 'Event', 'イベント', 7, 22, 1, 'ユーザーの操作やシステムの出来事', 'クリック、キー入力、マウス移動など、ブラウザ上で発生する出来事。JavaScriptで検知して処理できる。', 'イベントが発生すると、イベントオブジェクトが生成され、登録されたハンドラに渡される。', 'ドアベル。誰かがベルを鳴らした（イベント発生）ら、出迎える（処理する）。', 'イベントの種類は非常に多い。click、change、submit、keydown、load など、用途に応じて選ぶ。', ARRAY['event-listener', 'event-handler', 'prevent-default'], '「Event は、ユーザーの操作を検知する仕組みだ」'),
  ('event-listener', 'Event listener', 'イベントリスナー', 7, 23, 1, 'イベントを「聞く」仕組み', '特定のイベントが発生したときに、指定した関数を実行するように登録する仕組み。', 'element.addEventListener(''click'', handler) で登録。removeEventListener で解除。', '見張り番。「クリックされたら教えて」と頼んでおく。発生したら報告してくれる。', 'リスナーを登録したら、不要になったら解除する。メモリリークの原因になることがある。', ARRAY['event', 'event-handler', 'callback'], '「Event listener は、イベントを待ち受ける番人のようなものだ」'),
  ('event-handler', 'Event handler', 'イベントハンドラ', 7, 24, 1, 'イベント発生時に実行される関数', 'イベントが発生したときに呼び出される関数。イベントオブジェクトを引数として受け取る。', 'function handleClick(event) { ... } のように定義し、addEventListener で登録する。', 'イベント発生時の対応マニュアル。「こうなったらこうする」という手順書。', 'ハンドラ内で重い処理をすると、UIがブロックされる。必要に応じて非同期処理にする。', ARRAY['event', 'event-listener', 'callback'], '「Event handler は、イベント発生時に実行される処理そのものだ」'),
  ('prevent-default', 'Prevent default', 'プリベントデフォルト', 7, 25, 2, 'ブラウザの既定動作を止める', 'イベントのデフォルト動作（リンク遷移、フォーム送信など）を無効化するメソッド。', 'event.preventDefault() をハンドラ内で呼ぶ。フォームのsubmitでページリロードを防ぐなど。', '「いつもの動作をやめてください」というお願い。自動ドアが開くのを止めるような感じ。', '必要な場面でのみ使う。過度に使うと、ユーザーの期待する動作が阻害される。', ARRAY['event', 'event-handler', 'form'], '「preventDefault() で、ブラウザの既定動作を止められる」'),
  ('settimeout', 'setTimeout', 'セットタイムアウト', 7, 26, 1, '指定時間後に1回だけ実行', '指定したミリ秒後に、関数を1回だけ実行するタイマー関数。', 'setTimeout(callback, 1000) で1秒後にcallbackを実行。clearTimeoutでキャンセル可能。', 'アラーム。「5分後に起こして」とセットすると、5分後に1回だけ鳴る。', '時間は保証されない（最小でも指定時間後）。正確なタイミングが必要な処理には不向き。', ARRAY['setinterval', 'callback', 'async'], '「setTimeout は、一定時間後に処理を実行する」'),
  ('setinterval', 'setInterval', 'セットインターバル', 7, 27, 1, '指定間隔で繰り返し実行', '指定したミリ秒間隔で、関数を繰り返し実行するタイマー関数。', 'setInterval(callback, 1000) で1秒ごとにcallbackを実行。clearIntervalで停止。', '目覚まし時計のスヌーズ機能。一定間隔で何度も鳴る。止めるまで続く。', 'コンポーネントがアンマウントされてもintervalが残り続けることがある。クリーンアップを忘れずに。', ARRAY['settimeout', 'callback', 'loop'], '「setInterval は、一定間隔で処理を繰り返す」'),
  ('map-function', 'Map function', 'マップ関数', 7, 28, 1, '配列の各要素を変換して新しい配列を作る', '配列の各要素に関数を適用し、その結果から新しい配列を作成するメソッド。', '[1, 2, 3].map(x => x * 2) は [2, 4, 6] を返す。元の配列は変更されない。', '工場のライン。入ってきた材料（要素）を1つずつ加工（変換）して、新しい製品（配列）にする。', 'mapは新しい配列を返す。戻り値を使わないならforEachを使う方が適切。', ARRAY['filter-function', 'reduce-function', 'foreach'], '「Map は、配列の各要素を変換する」'),
  ('filter-function', 'Filter function', 'フィルター関数', 7, 29, 1, '条件に合う要素だけを取り出す', '配列の各要素を条件でテストし、条件を満たす要素だけで新しい配列を作成するメソッド。', '[1, 2, 3, 4].filter(x => x > 2) は [3, 4] を返す。元の配列は変更されない。', 'ふるい。大きさの条件に合うものだけが通過し、残りは落ちる。', '条件に合う要素がない場合、空配列を返す（エラーにはならない）。', ARRAY['map-function', 'find', 'reduce-function'], '「Filter は、条件に合う要素だけを取り出す」'),
  ('reduce-function', 'Reduce function', 'リデュース関数', 7, 30, 2, '配列を1つの値にまとめる', '配列の要素を順に処理し、単一の値（合計、オブジェクト、配列など）にまとめるメソッド。', '[1, 2, 3].reduce((acc, cur) => acc + cur, 0) は 6 を返す。初期値は第2引数で指定。', '雪だるま作り。転がすたびに雪（要素）が加わって、最終的に1つの大きな雪だるま（結果）になる。', '初期値を省略すると配列の最初の要素が使われる。空配列でエラーになるので注意。', ARRAY['map-function', 'filter-function', 'foreach'], '「Reduce は、配列を1つの値にまとめる。最も強力だが、難しい術だ」'),
  ('foreach', 'ForEach', 'フォーイーチ', 7, 31, 1, '配列の各要素に処理を実行', '配列の各要素に対して、指定した関数を実行するメソッド。戻り値はなく、副作用のための処理に使う。', '[1, 2, 3].forEach(x => console.log(x)) で各要素を出力。map と違い、新しい配列は作らない。', '出席確認。一人ずつ名前を呼んで確認していく。結果の名簿を作るわけではない。', 'forEachは途中で抜けられない（breakが使えない）。途中で抜けたいならfor...ofを使う。', ARRAY['map-function', 'loop', 'iteration'], '「forEach は、各要素に対して処理を実行する。戻り値は不要なときに使う」'),
  ('find', 'Find', 'ファインド', 7, 32, 1, '条件に合う最初の要素を取得', '配列の中から、条件を満たす最初の要素を返すメソッド。見つからなければundefinedを返す。', '[1, 2, 3].find(x => x > 1) は 2 を返す。最初に条件を満たした時点で検索終了。', '落とし物を探す。条件に合うものを見つけたら、そこで探索終了。', '見つからない場合の undefined を考慮する。オプショナルチェイニングや条件分岐で対応。', ARRAY['filter-function', 'index', 'array'], '「Find は、条件に合う最初の要素を見つける」'),
  ('console-log', 'Console log', 'コンソールログ', 7, 33, 1, '開発者ツールに値を出力する', 'ブラウザの開発者ツール（コンソール）にメッセージや値を出力するメソッド。デバッグに必須。', 'console.log(''Hello''); や console.log(variable); で値を確認できる。', '独り言を記録するメモ。プログラムの途中経過を自分だけに見えるように書き出す。', '本番環境にconsole.logを残さない。デバッグ用のログは削除するか、ログレベルを管理する。', ARRAY['debug', 'dev-tools', 'breakpoint'], '「console.log() は、値を確認する基本中の基本だ。デバッグの第一歩」'),
  ('get', 'Get', 'ゲット', 7, 34, 2, 'プロパティ取得時に実行されるメソッド', 'オブジェクトのプロパティにアクセスしたときに自動的に実行されるgetterメソッド。', 'get propName() { return this._prop; } で定義。obj.propName でアクセスすると実行される。', '自動ドア。近づいた（アクセスした）だけで、自動的にドアが開く（処理が実行される）。', 'getterで重い処理をすると、プロパティアクセスのたびにパフォーマンスに影響する。', ARRAY['property', 'object', 'method'], '「Get と Set は、プロパティへのアクセスをカスタマイズする術だ」'),
  ('typeof', 'Typeof', 'タイプオブ', 7, 35, 1, '値の型を調べる演算子', '値のデータ型を文字列で返す演算子。''string''、''number''、''boolean''、''object'' などを返す。', 'typeof 42 は ''number''、typeof ''hello'' は ''string'' を返す。', '素材の鑑定。「これは木です」「これは金属です」と、素材（型）を判定する。', 'typeof null は ''object'' を返す（JavaScriptの歴史的バグ）。nullチェックは === null を使う。', ARRAY['data-type', 'primitive', 'object'], '「typeof で、値の型を確認できる」'),
  ('node-js', 'Node.js', 'ノードジェイエス', 7, 36, 2, 'サーバーで動くJavaScript環境', 'ブラウザの外でJavaScriptを実行できる環境。サーバーサイド開発、CLI ツール、ビルドツールなどに使用。', 'V8エンジン（Chromeと同じ）を使用。npm（パッケージマネージャー）でライブラリを管理。', 'JavaScriptの「出張版」。ブラウザという職場を離れて、サーバーでも働けるようになった。', 'ブラウザ用のAPI（window、documentなど）はNode.jsでは使えない。環境の違いを意識する。', ARRAY['javascript', 'npm', 'backend'], '「Node.js は、サーバーで JavaScript を動かす環境だ」'),
  ('zod', 'Zod', 'ゾッド', 7, 37, 2, 'TypeScript向けの型検証ライブラリ', '実行時にデータの型を検証するTypeScript向けライブラリ。APIレスポンスやフォーム入力のバリデーションに使用。', 'z.object({ name: z.string() }).parse(data) でデータを検証。不正なら例外をスロー。', '入国審査官。「パスポート（型）は正しいですか？」とチェックして、不正なら入国拒否。', 'TypeScriptの型は実行時に消える。Zodは実行時にも型チェックできる点が強み。', ARRAY['typescript', 'validation', 'schema'], '「Zod は、実行時にもデータの型を検証するライブラリだ」'),
  ('library-import', 'Library import', 'ライブラリインポート', 7, 38, 1, '外部ライブラリを読み込むこと', 'npm等でインストールした外部ライブラリを、自分のコードで使えるようにimportすること。', 'import React from ''react''; のように、パッケージ名を指定してimportする。', '道具を借りる。自分で作らなくても、便利な道具（ライブラリ）を借りて使える。', 'バンドルサイズが大きくなりすぎないよう注意。必要な機能だけをimportする。', ARRAY['import', 'npm', 'package'], '「外部のライブラリを Import して使う。車輪の再発明を避けるのだ」'),
  ('utility', 'Utility', 'ユーティリティ', 7, 39, 1, '汎用的に使える便利な関数', '特定の機能に依存せず、様々な場面で使える汎用的な関数や機能。日付フォーマット、配列操作などが典型。', 'utils/ フォルダにまとめることが多い。lodashなどはユーティリティライブラリの代表。', '万能ナイフ。いろんな場面で役立つ、汎用性の高い道具。', '「ユーティリティ」が肥大化しがち。関連する機能ごとにファイルを分けて整理する。', ARRAY['function', 'library-import', 'modularity'], '「Utility は、いろんな場面で使える便利な関数群だ」'),
  ('parsing', 'Parsing', 'パース', 7, 40, 2, '文字列を解析して構造化データに変換', '文字列を解析して、プログラムが扱いやすい形式（オブジェクト、数値など）に変換すること。', 'JSON.parse(jsonString) でJSON文字列をオブジェクトに変換。parseInt(''42'') で文字列を数値に。', '翻訳。外国語（文字列）を自国語（構造化データ）に変換して、理解できるようにする。', '不正なJSON文字列をparseするとエラーになる。try/catchでエラーハンドリングする。', ARRAY['json', 'string', 'data-type'], '「Parsing は、文字列をデータ構造に変換する術。JSON.parse() がその代表だ」')
ON CONFLICT (id) DO UPDATE SET
  term = EXCLUDED.term,
  term_ja = EXCLUDED.term_ja,
  chapter_id = EXCLUDED.chapter_id,
  order_index = EXCLUDED.order_index,
  difficulty = EXCLUDED.difficulty,
  one_liner = EXCLUDED.one_liner,
  definition = EXCLUDED.definition,
  mechanism = EXCLUDED.mechanism,
  analogy = EXCLUDED.analogy,
  pitfall = EXCLUDED.pitfall,
  related_terms = EXCLUDED.related_terms,
  story_context = EXCLUDED.story_context;
